In [5]:
import torch

# Check if GPU is available and print GPU information
if torch.cuda.is_available():
    print("GPU is available")
    print(f"Number of GPUs: {torch.cuda.device_count()}")
    for i in range(torch.cuda.device_count()):
        print(f"GPU {i}: {torch.cuda.get_device_name(i)}")
else:
    print("GPU is not available")

GPU is not available


In [6]:
# Create a tensor
tens = torch.tensor([[1,2,3],[4,5,6]])
print(tens)

# Get shape
print(tens.shape)

# Get data type
print(tens.dtype)

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])
torch.int64


In [7]:
import torch.nn as nn  # neural network module

input_tensor = torch.tensor([0.3471, 0.4547, -0.2356])

# Create a linear layer: 3 inputs -> 2 outputs
linear_layer = nn.Linear(in_features=3, out_features=2)

# Pass input through the linear layer
output = linear_layer(input_tensor)
print(output)

# Print weights and biases
print(linear_layer.weight)
print(linear_layer.bias)

tensor([-0.1518, -0.6213], grad_fn=<ViewBackward0>)
Parameter containing:
tensor([[ 0.5481,  0.1480, -0.3569],
        [ 0.3619, -0.5508, -0.0148]], requires_grad=True)
Parameter containing:
tensor([-0.4935, -0.4999], requires_grad=True)
