# Team Galaxy Assignment 01

### A. Importing Libraries

In [4]:
import torch
import pandas as pd
import torch.nn as nn
from sklearn.preprocessing import LabelEncoder

### B. Importing data to Panda Dataframe

In [5]:
url = 'https://raw.githubusercontent.com/m-bermudez/ISM6251-ML-Project/refs/heads/main/EmployeeAttrition.csv'
df = pd.read_csv(url)
df.head()

Age Attrition     BusinessTravel  DailyRate              Department  \
0   41       Yes      Travel_Rarely       1102                   Sales   
1   49        No  Travel_Frequently        279  Research & Development   
2   37       Yes      Travel_Rarely       1373  Research & Development   
3   33        No  Travel_Frequently       1392  Research & Development   
4   27        No      Travel_Rarely        591  Research & Development   

   DistanceFromHome  Education EducationField  EmployeeCount  EmployeeNumber  \
0                 1          2  Life Sciences              1               1   
1                 8          1  Life Sciences              1               2   
2                 2          2          Other              1               4   
3                 3          4  Life Sciences              1               5   
4                 2          1        Medical              1               7   

   ...  RelationshipSatisfaction StandardHours  StockOptionLevel  \
0  ...                         1            80                 0   
1  ...                         4            80                 1   
2  ...                         2            80                 0   
3  ...                         3            80                 0   
4  ...                         4            80                 1   

   TotalWorkingYears  TrainingTimesLastYear WorkLifeBalance  YearsAtCompany  \
0                  8                      0               1               6   
1                 10                      3               3              10   
2                  7                      3               3               0   
3                  8                      3               3               8   
4                  6                      3               3               2   

  YearsInCurrentRole  YearsSinceLastPromotion  YearsWithCurrManager  
0                  4                        0                     5  
1                  7                        1                     7  
2                  0                        0                     0  
3                  7                        3                     0  
4                  2                        2                     2  

[5 rows x 35 columns]

### C. Re-factoring the Data

In [6]:
type_map = {
    'object': 'category'
}
for column in df.columns:
    original_data_type = df[column].dtype.name
    if original_data_type in type_map:
        df[column] = df[column].astype(type_map[original_data_type])

### D. Encoding Data

In [7]:
categorical_cols = df.select_dtypes(include=['category']).columns
label_encoders = {}

print("Encoding Guide:")
print("-" * 50)

for col in categorical_cols:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])
    label_encoders[col] = le

    mapping = {index: label for index, label in enumerate(le.classes_)}
    print(f"Column: {col}")
    for original, encoded in mapping.items():
        print(f"  {encoded} -> {original}")
    print("-" * 50)

Encoding Guide:
--------------------------------------------------
Column: Attrition
  No -> 0
  Yes -> 1
--------------------------------------------------
Column: BusinessTravel
  Non-Travel -> 0
  Travel_Frequently -> 1
  Travel_Rarely -> 2
--------------------------------------------------
Column: Department
  Human Resources -> 0
  Research & Development -> 1
  Sales -> 2
--------------------------------------------------
Column: EducationField
  Human Resources -> 0
  Life Sciences -> 1
  Marketing -> 2
  Medical -> 3
  Other -> 4
  Technical Degree -> 5
--------------------------------------------------
Column: Gender
  Female -> 0
  Male -> 1
--------------------------------------------------
Column: JobRole
  Healthcare Representative -> 0
  Human Resources -> 1
  Laboratory Technician -> 2
  Manager -> 3
  Manufacturing Director -> 4
  Research Director -> 5
  Research Scientist -> 6
  Sales Executive -> 7
  Sales Representative -> 8
------------------------------------------

### E. GPU Availability Check
Check if GPU is available and print GPU information

In [1]:
if torch.cuda.is_available():
    print("GPU is available")
    print(f"Number of GPUs: {torch.cuda.device_count()}")
    for i in range(torch.cuda.device_count()):
        print(f"GPU {i}: {torch.cuda.get_device_name(i)}")
else:
    print("GPU is not available")

GPU is not available


### F. Tensor Creation
Creating a tensor, while also getting tensor shape and data type

In [6]:
# Create a tensor
tens = torch.tensor([[1,2,3],[4,5,6]])
print(tens)

# Get shape
print(tens.shape)

# Get data type
print(tens.dtype)

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])
torch.int64


In [7]:
input_tensor = torch.tensor([0.3471, 0.4547, -0.2356])

# Create a linear layer: 3 inputs -> 2 outputs
linear_layer = nn.Linear(in_features=3, out_features=2)

# Pass input through the linear layer
output = linear_layer(input_tensor)
print(output)

# Print weights and biases
print(linear_layer.weight)
print(linear_layer.bias)

tensor([-0.1518, -0.6213], grad_fn=<ViewBackward0>)
Parameter containing:
tensor([[ 0.5481,  0.1480, -0.3569],
        [ 0.3619, -0.5508, -0.0148]], requires_grad=True)
Parameter containing:
tensor([-0.4935, -0.4999], requires_grad=True)
