In [1]:
import torch

# Check if GPU is available and print GPU information
if torch.cuda.is_available():
    print("GPU is available")
    print(f"Number of GPUs: {torch.cuda.device_count()}")
    for i in range(torch.cuda.device_count()):
        print(f"GPU {i}: {torch.cuda.get_device_name(i)}")
else:
    print("GPU is not available")

GPU is available
Number of GPUs: 1
GPU 0: NVIDIA GeForce RTX 4070 Ti SUPER


In [2]:
# Create a tensor
tens = torch.tensor([[1,2,3],[4,5,6]])
print(tens)

# Get shape
print(tens.shape)

# Get data type
print(tens.dtype)

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])
torch.int64


In [3]:
import torch.nn as nn  # neural network module

input_tensor = torch.tensor([0.3471, 0.4547, -0.2356])

# Create a linear layer: 3 inputs -> 2 outputs
linear_layer = nn.Linear(in_features=3, out_features=2)

# Pass input through the linear layer
output = linear_layer(input_tensor)
print(output)

# Print weights and biases
print(linear_layer.weight)
print(linear_layer.bias)

tensor([-0.2796,  0.1021], grad_fn=<ViewBackward0>)
Parameter containing:
tensor([[-0.3054,  0.0689,  0.5136],
        [ 0.2273,  0.5029,  0.1349]], requires_grad=True)
Parameter containing:
tensor([-0.0839, -0.1737], requires_grad=True)
